eawc

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -391,3 +391,80 @@ jobs:
               repo: context.repo.repo,
               body: result
             });
+
+  create-release-tag:
+    needs: page_speed_analysis
+    runs-on: ubuntu-latest
+    timeout-minutes: 3
+
+    steps:
+      - name: リポジトリをチェックアウト
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+
+      - name: 前回のリリースタグを取得する
+        id: fetch_previous_tag
+        run: |
+          echo "pre_tag=$(curl -H 'Accept: application/vnd.github.v3+json' -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .tag_name)" >> $GITHUB_OUTPUT
+
+      - name: タグを生成する 「{YYYY.MM.DD}-{異なる日のリリース回数}.{当日リリース回数}」
+        id: generate_release_tag
+        run: |
+          today=$(date +'%Y.%m.%d')
+          pre_release_date=$(echo ${{ steps.fetch_previous_tag.outputs.pre_tag }} | awk -F'-' '{print $1}')
+          pre_release_count=$(echo ${{ steps.fetch_previous_tag.outputs.pre_tag }} | awk -F'-' '{print $2}')
+          if [[ ! $pre_release_date = $today ]]; then
+            pre_release_count=0
+          fi
+          echo "release_tag=$today-$(($pre_release_count + 1))" >> $GITHUB_OUTPUT
+
+      - name: PRのDescriptionを取得しマークダウン形式に変換する
+        id: fetch_pr_description
+        run: |
+          echo "pr_description=$(curl -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
+            'https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number}}' \
+            | jq .body | awk '{if ($0 == "null") print ""; else print}')" >> $GITHUB_OUTPUT
+
+      - name: 前回リリースからの差分をもとに、変更点を取得する
+        id: generate_changes
+        run: |
+          echo "changes=$(
+          curl -X POST \
+            -H 'Accept: application/vnd.github.v3+json' \
+            -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
+            https://api.github.com/repos/${{ github.repository }}/releases/generate-notes \
+            -d '{
+              "tag_name": "${{ steps.generate_release_tag.outputs.release_tag }}",
+              "previous_tag_name": "${{ steps.fetch_previous_tag.outputs.pre_tag }}",
+              "target_commitish": "main"
+            }' | jq .body
+          )" >> $GITHUB_OUTPUT
+
+      - name: リリースノートの本文を作成する
+        id: prepare_release_note
+        run: |
+          echo "release_note_body=$(echo \
+            ${{ steps.fetch_pr_description.outputs.pr_description }} \
+            ${{ steps.generate_changes.outputs.changes }} \
+            | sed 's/\\"//g' | sed 's/["“]//g')" >> $GITHUB_OUTPUT
+
+      - name: タグを切り、リリースノートを作成する
+        run: |
+          response=$(curl -X POST \
+            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+            -d "{ \
+              \"tag_name\": \"${{ steps.generate_release_tag.outputs.release_tag }}\", \
+              \"target_commitish\": \"main\", \
+              \"name\": \"${{ steps.generate_release_tag.outputs.release_tag }}\", \
+              \"body\": \"${{ steps.prepare_release_note.outputs.release_note_body }}\" \
+            }" \
+            -w "%{http_code}" \
+            -o response_body.txt \
+            https://api.github.com/repos/${{ github.repository }}/releases)
+            status_code=$(tail -n1 <<< "$response")
+            echo "Status Code: $status_code"
+            body=$(cat response_body.txt)
+            echo "Response Body: $body"
+            if [ $status_code -ne 201 ]; then
+              echo "::error:: リリースの作成に失敗しました。"
+              exit 1
+            fi
